"""Generate the Tasks icon assets from ASCII art.

Two formats, because the firmware has two icon pipelines:

  legacy (GfxRenderer::drawIcon, used by the themes' home menu) is PRE-ROTATED:
      drawPixel(x + (size - 1 - row), y + col)
  so a screen pixel (sx, sy) lives at stored row = size-1-sx, col = sy.

  SDK (freeink::Icon, used by fui list rows) is plain row-major, not rotated.

Both are 1bpp MSB-first with bit 0 = ink.
"""

import os

# Written next to the other icons, so the script can be run from any directory.
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "components", "icons")

# ---------------------------------------------------------------- art helpers


def blank(size):
    return [[0] * size for _ in range(size)]


def rect(px, x0, y0, x1, y1, t=1):
    for i in range(t):
        for x in range(x0, x1 + 1):
            px[y0 + i][x] = 1
            px[y1 - i][x] = 1
        for y in range(y0, y1 + 1):
            px[y][x0 + i] = 1
            px[y][x1 - i] = 1


def fill(px, x0, y0, x1, y1):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            px[y][x] = 1


def stamp(px, art, x0, y0):
    """Paint a multi-line string of '#' at (x0, y0)."""
    for dy, line in enumerate(art.strip("\n").split("\n")):
        for dx, ch in enumerate(line):
            if ch == "#":
                px[y0 + dy][x0 + dx] = 1


TICK_SMALL = """
......##
.....##.
#....##.
##..##..
.####...
..##....
"""

TICK_BIG = """
.......###
......###.
......###.
#....###..
##..###...
###.###...
.######...
..####....
...##.....
"""


# ------------------------------------------------------------------ encoders


def encode_rows(px, size):
    """Row-major MSB-first, bit 0 = ink (so invert: art 1 -> bit 0)."""
    row_bytes = (size + 7) // 8
    out = []
    for row in range(size):
        for b in range(row_bytes):
            byte = 0
            for bit in range(8):
                col = b * 8 + bit
                ink = col < size and px[row][col]
                if not ink:
                    byte |= 1 << (7 - bit)
            out.append(byte)
    return out


def encode_legacy(px, size):
    """Pre-rotated for drawIcon: stored[row][col] is screen (size-1-row, col)."""
    rot = blank(size)
    for sy in range(size):
        for sx in range(size):
            if px[sy][sx]:
                rot[size - 1 - sx][sy] = 1
    return encode_rows(rot, size)


def fmt(data, per_line=16, indent="    "):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join("0x%02X" % b for b in data[i:i + per_line])
        lines.append(indent + chunk + ("," if i + per_line < len(data) else ""))
    return "\n".join(lines)


# --------------------------------------------------------------- the artwork


def art_tasks_32():
    """Home-menu icon: a clipboard with three ticked lines."""
    px = blank(32)
    rect(px, 3, 3, 28, 30, t=2)      # clipboard body
    fill(px, 11, 0, 20, 4)           # the clip at the top
    fill(px, 13, 1, 18, 3)           # (hollowed below)
    for y in (10, 17, 24):
        stamp(px, TICK_SMALL, 6, y)
        fill(px, 17, y + 2, 25, y + 3)
    # Re-hollow the clip so it reads as a clip, not a solid tab.
    for y in range(2, 4):
        for x in range(14, 18):
            px[y][x] = 0
    return px


def art_box_24(state):
    """List-row state glyph: empty box / dashed box / ticked box.

    The dash is the conventional indeterminate-checkbox glyph, and at 24px it
    stays unmistakably distinct from both the empty box and the tick.
    """
    px = blank(24)
    rect(px, 3, 3, 20, 20, t=2)
    if state == "progress":
        fill(px, 7, 10, 16, 13)
    elif state == "done":
        stamp(px, TICK_BIG, 7, 7)
    return px


# -------------------------------------------------------------------- output

with open(os.path.join(OUT, "tasks.h"), "w", newline="\n") as f:
    f.write("#pragma once\n#include <cstdint>\n\n")
    f.write("// Generated by scripts/gen_task_icons.py. Do not edit by hand.\n")
    f.write("\n// size: 32x32 (pre-rotated, as GfxRenderer::drawIcon expects)\n")
    f.write("static const uint8_t TasksIcon[] = {\n")
    f.write(fmt(encode_legacy(art_tasks_32(), 32)))
    f.write("\n};\n")

with open(os.path.join(OUT, "taskStateIcons.h"), "w", newline="\n") as f:
    f.write('#pragma once\n\n#include "Icon.h"\n\n')
    f.write("// Generated by scripts/gen_task_icons.py. Do not edit by hand.\n")
    f.write("// Task state glyphs for FreeInkUI list rows (24px, row-major, bit 0 = ink).\n")
    for name in ("open", "progress", "done"):
        data = encode_rows(art_box_24(name), 24)
        f.write("\nstatic const uint8_t icon_task_%s_24_bits[] = {\n" % name)
        f.write(fmt(data, per_line=18))
        f.write("\n};\n")
        f.write("static const freeink::Icon icon_task_%s_24 = {24, 24, 12, icon_task_%s_24_bits};\n"
                % (name, name))

print("wrote tasks.h and taskStateIcons.h")

for label, px in (("tasks32", art_tasks_32()),
                  ("open", art_box_24("open")),
                  ("progress", art_box_24("progress")),
                  ("done", art_box_24("done"))):
    print("\n" + label)
    for row in px:
        print("".join("#" if v else "." for v in row))
