"""Generate the Text editor home-menu icon and the "New list" row icon.

Both come from stock Lucide SVGs in the SDK, rasterized with cairosvg (already
a scripts/requirements.txt dependency, so no rsvg-convert is needed):

  EditorIcon         square-pen, 32px, legacy format for GfxRenderer::drawIcon
                     (the themes' home menu). PRE-ROTATED:
                         drawPixel(x + (size - 1 - row), y + col)
                     so a screen pixel (sx, sy) lives at stored row = size-1-sx,
                     col = sy. Same layout as scripts/gen_task_icons.py.
  icon_file_plus_24  file-plus, 24px, freeink::Icon for FreeInkUI list rows:
                     plain row-major, not rotated, optical center baked in like
                     the SDK's gen_icons.py.

Both are 1bpp MSB-first with bit 0 = ink. Run from any directory:
    python scripts/gen_editor_icons.py
"""

import io
import os

import cairosvg
from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LUCIDE = os.path.join(ROOT, "freeink-sdk", "libs", "assets", "Icons", "lucide", "icons")
OUT = os.path.join(ROOT, "src", "components", "icons", "editor.h")

# Same cut-off as the SDK generator: keeps 2px Lucide strokes solid when small.
THRESHOLD = 110


def rasterize(name, size):
    """Lucide SVG -> size x size grid of 0/1, 1 = ink."""
    png = cairosvg.svg2png(url=os.path.join(LUCIDE, name + ".svg"), output_width=size, output_height=size)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    lum = bg.convert("L").load()
    return [[1 if lum[x, y] < THRESHOLD else 0 for x in range(size)] for y in range(size)]


def encode_rows(px, size):
    """Row-major MSB-first, bit 0 = ink (so invert: art 1 -> bit 0)."""
    row_bytes = (size + 7) // 8
    out = []
    for row in range(size):
        for b in range(row_bytes):
            byte = 0
            for bit in range(8):
                col = b * 8 + bit
                if not (col < size and px[row][col]):
                    byte |= 1 << (7 - bit)
            out.append(byte)
    return out


def encode_legacy(px, size):
    """Pre-rotated for drawIcon: stored[row][col] is screen (size-1-row, col)."""
    rot = [[0] * size for _ in range(size)]
    for sy in range(size):
        for sx in range(size):
            if px[sy][sx]:
                rot[size - 1 - sx][sy] = 1
    return encode_rows(rot, size)


def optical_center(px, size):
    ys = [y for y in range(size) for x in range(size) if px[y][x]]
    return round(sum(ys) / len(ys)) if ys else size // 2


def fmt(data, per_line=16, indent="    "):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join("0x%02X" % b for b in data[i:i + per_line])
        lines.append(indent + chunk + ("," if i + per_line < len(data) else ""))
    return "\n".join(lines)


editor = rasterize("square-pen", 32)
plus = rasterize("file-plus", 24)

with open(OUT, "w", newline="\n") as f:
    f.write('#pragma once\n\n#include <cstdint>\n\n#include "Icon.h"\n\n')
    f.write("// Generated by scripts/gen_editor_icons.py from Lucide SVGs. Do not edit by hand.\n")
    f.write("\n// Text editor home-menu icon (square-pen). size: 32x32 (pre-rotated, as\n")
    f.write("// GfxRenderer::drawIcon expects)\n")
    f.write("static const uint8_t EditorIcon[] = {\n")
    f.write(fmt(encode_legacy(editor, 32)))
    f.write("\n};\n")
    f.write("\n// \"New list\" row icon (file-plus) for FreeInkUI list rows (24px, row-major).\n")
    f.write("static const uint8_t icon_file_plus_24_bits[] = {\n")
    f.write(fmt(encode_rows(plus, 24), per_line=18))
    f.write("\n};\n")
    f.write("static const freeink::Icon icon_file_plus_24 = {24, 24, %d, icon_file_plus_24_bits};\n"
            % optical_center(plus, 24))

print("wrote", os.path.normpath(OUT))
